// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puddrfjzujikfehidzky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZGRyZmp6dWppa2ZlaGlkemt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTQwOTAsImV4cCI6MjA3MDQzMDA5MH0.ZYScbz1fXKOD2T194TO0EXnR0UOpsTTuj7HpLHX67v4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});